"""remove redundant documents id index

Revision ID: 214b5a21d456
Revises: 69d06f228c5f
Create Date: 2026-08-25 23:06:25.374636
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '214b5a21d456'
down_revision: Union[str, None] = '69d06f228c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###
